AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates Lambda and HttpAPI using ECR repository for the spam detector Lambda function.

Globals:
  Function:
    Timeout: 30
    MemorySize: 200

Resources:
  SpamDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 358362547251.dkr.ecr.eu-west-1.amazonaws.com/ml-spam-detector:latest # !Sub "${ECRRepoUri}:latest" #ml-spam-detector-api-lambda:latest
      Events:
        PostPredict:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: post
            ApiId: !Ref SpamDetectorApi

  SpamDetectorApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
        AllowOrigins:
          - "*"
