version = 0.1
[default.deploy.parameters]
stack_name = "ml-spam-detector-lambda-apigateway"
resolve_s3 = true
s3_prefix = "ml-spam-detector-lambda-apigateway"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
